<?php
$menu_arrays = array(
    '基本运营数据'=>array(
        array('index'=>'newweb/nowtime',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'实时数据'),
        array('index'=>'overview',      'open'=>'open1',    'Suffix'=>'php',      'name'=>'游戏数据总览'),
                 
    ),
    '自定义游戏数据'=>array(
        array('index'=>'trade_total',      'open'=>'open1',    'Suffix'=>'php',      'name'=>'交易所统计'),
        array('index'=>'newweb/yu_currency',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'仙玉详情'),
        array('index'=>'newweb/count_yu_currency',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'仙玉统计'),
        array('index'=>'newweb/bang_currency',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'帮贡详情'),
        array('index'=>'newweb/count_bang_currency',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'帮贡统计'),
        array('index'=>'newweb/yin_currency',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'银币详情'),
        array('index'=>'newweb/count_yin_currency',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'银币统计'),
        array('index'=>'newweb/zx_quest',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙任务'),
        array('index'=>'newweb/count_quest',   'open'=>'open3',   'Suffix'=>'php',    'name'=>'任务统计' ),
        array('index'=>'newweb/zx_level',   'open'=>'open3',   'Suffix'=>'php',    'name'=>'玩家等级统计' ),
        array('index'=>'newweb/zx_dup',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙副本'),
        array('index'=>'newweb/count_dup',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'副本统计'),
        array('index'=>'newweb/zx_item',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙物品'),
        array('index'=>'newweb/zx_equipslot',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙装备槽'),
        array('index'=>'newweb/zx_fabao',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙法宝'),
        array('index'=>'newweb/zx_honor',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙头衔'),
        array('index'=>'newweb/count_honor',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'头衔统计'),
        array('index'=>'newweb/zx_closeness',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙亲密度'),
        array('index'=>'newweb/zx_septlvup',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙仙踪升级'),       
        array('index'=>'newweb/zx_shop',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'斩仙商店'),
        
    ),
    
    '收入'=>array(
        array('index'=>'newweb/v_serversummary',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'服务器汇总'),
        array('index'=>'newweb/syincome',             'open'=>'open3',    'Suffix'=>'php',      'name'=>'[手游]数据汇总'),
        array('index'=>'total',                       'open'=>'open1',    'Suffix'=>'html',     'name'=>'总收入'),
        array('index'=>'totalh',                      'open'=>'open1',    'Suffix'=>'html',     'name'=>'分时总收入'),
        array('index'=>'server',                      'open'=>'open1',    'Suffix'=>'html',     'name'=>'服务器收入'),
        array('index'=>'newweb/v_acc_income',         'open'=>'open3',    'Suffix'=>'php',      'name'=>'帐号收入'),
        array('index'=>'newweb/v_newregpay',          'open'=>'open3',    'Suffix'=>'php',      'name'=>'新注册付费'),
        array('index'=>'regdays',                     'open'=>'open1',    'Suffix'=>'html',     'name'=>'30日付费'),
        array('index'=>'paymonth',                    'open'=>'open1',    'Suffix'=>'html',     'name'=>'月付费分析'),
        array('index'=>'newweb/v_day_qd_date',        'open'=>'open3',    'Suffix'=>'php',      'name'=>'渠道日数据'),
    ),
    '在线'=>array(
        array('index'=>'onlinecnt',                   'open'=>'open1',    'Suffix'=>'html',     'name'=>'分时在线'),
        array('index'=>'ht_all_online',               'open'=>'open3',    'Suffix'=>'php',      'name'=>'全游戏总在线'),
    ),
    '查询工具'=>array(
        array('index'=>'newweb/v_acc_detail',         'open'=>'open3',    'Suffix'=>'php',      'name'=>'账号明细'),
        array('index'=>'bi_exceladd3',         'open'=>'open3',    'Suffix'=>'php',      'name'=>'excel->账号明细'),
        array('index'=>'bi_exceladd1',         'open'=>'open3',    'Suffix'=>'php',      'name'=>'excel->账号明细（角色id)'),
        array('index'=>'newweb/v_giftinfo',           'open'=>'open3',    'Suffix'=>'php',      'name'=>'发放物品查询'),
        array('index'=>'newweb/v_zone_msg',           'open'=>'open3',    'Suffix'=>'php',      'name'=>'区服转换'),
        array('index'=>'newweb/v_mailinfo',           'open'=>'open3',    'Suffix'=>'php',      'name'=>'邮件记录查询'),
        array('index'=>'newweb/v_showban',            'open'=>'open3',    'Suffix'=>'php',      'name'=>'show_ban'),
        array('index'=>'newweb/v_acc_detail2',        'open'=>'open3',    'Suffix'=>'php',      'name'=>'玩家状态查询'),
        array('index'=>'show_inside_error',           'open'=>'open3',    'Suffix'=>'php',      'name'=>'前端报错查询'),
        array('index'=>'show_inside_error2',           'open'=>'open3',    'Suffix'=>'php',      'name'=>'前端报错查询2'),
        array('index'=>'newweb/v_suggest',            'open'=>'open3',    'Suffix'=>'php',      'name'=>'玩家建议反馈'),
        array('index'=>'shentonglist',            'open'=>'open3',    'Suffix'=>'php',      'name'=>'战力排行'),
        array('index'=>'newweb/v_diaocha1',            'open'=>'open3',    'Suffix'=>'php',      'name'=>'调查问卷'),
         array('index'=>'newweb/v_zonemsg',            'open'=>'open3',    'Suffix'=>'php',      'name'=>'zone_msg列表'),
	array('index'=>'newweb/v_zonemsg_list',            'open'=>'open3',    'Suffix'=>'php',      'name'=>'zone_msg列表2'),
    ),
    'GM工具'=>array(
        array('index'=>'gameactivity',                'open'=>'open2',    'Suffix'=>'php',      'name'=>'新服活动'),
        array('index'=>'shoplimit',                   'open'=>'open2',    'Suffix'=>'php',      'name'=>'配置限购'),
        array('index'=>'onekey_gameactivity',         'open'=>'open2',    'Suffix'=>'php',      'name'=>'一键开服活动'),
        array('index'=>'email',                       'open'=>'open2',    'Suffix'=>'php',      'name'=>'发送补偿'),
        array('index'=>'multiemails',                 'open'=>'open2',    'Suffix'=>'php',      'name'=>'发送补偿1'),
        array('index'=>'excelGift',                   'open'=>'open2',    'Suffix'=>'php',      'name'=>'批量发送补偿'),
        array('index'=>'gift',                        'open'=>'open2',    'Suffix'=>'php',      'name'=>'全服发送补偿'),
        array('index'=>'ht_excelGift',                'open'=>'open2',    'Suffix'=>'php',      'name'=>'excel补偿2'),
        array('index'=>'blacklist',                   'open'=>'open1',    'Suffix'=>'html',     'name'=>'黑名单'),
        array('index'=>'tester',                      'open'=>'open2',    'Suffix'=>'php',      'name'=>'白名单'),
        array('index'=>'newweb/v_ipbailist',          'open'=>'open3',    'Suffix'=>'php',      'name'=>'IP白名单'),
        array('index'=>'ht_gmcode',                   'open'=>'open2',    'Suffix'=>'php',      'name'=>'GM命令工具'),
        array('index'=>'banandgonggao',               'open'=>'open2',    'Suffix'=>'php',      'name'=>'封号、禁言、公告'),
        array('index'=>'newweb/v_gonggao',            'open'=>'open2',    'Suffix'=>'php',      'name'=>'定时公告工具'),
        array('index'=>'opGameactivity',              'open'=>'open2',    'Suffix'=>'php',      'name'=>'多服活动更新过期'),
        array('index'=>'newweb/v_timeing_gift',       'open'=>'open3',    'Suffix'=>'php',      'name'=>'定时全服补偿'),
        array('index'=>'sy_cdk_csv',                  'open'=>'open3',    'Suffix'=>'php',      'name'=>'CDK导入'),
        array('index'=>'cdk2',                  'open'=>'open3',    'Suffix'=>'php',      'name'=>'CDK导入带道具'),
        array('index'=>'sy_qbkm_csv',                 'open'=>'open3',    'Suffix'=>'php',      'name'=>'Q币卡密导入'),
        array('index'=>'uuseracc',                    'open'=>'open3',    'Suffix'=>'php',      'name'=>'进入玩家帐号'),
        array('index'=>'newweb/v_paylistadd',         'open'=>'open3',    'Suffix'=>'php',      'name'=>'未到账补单'),
        array('index'=>'start_server',                'open'=>'open3',    'Suffix'=>'php',      'name'=>'启动新服务器'),
        array('index'=>'newweb/v_auto_gift',          'open'=>'open3',    'Suffix'=>'php',      'name'=>'自动定时发送礼包'),
        array('index'=>'newweb/v_family',              'open'=>'open3',    'Suffix'=>'php',      'name'=>'家族查询管理'),
        array('index'=>'newweb/v_guozhan',            'open'=>'open3',    'Suffix'=>'php',      'name'=>'国战查看'),
        array('index'=>'newweb/v_guozhan_excel',      'open'=>'open2',    'Suffix'=>'php',      'name'=>'国战配置'),
        array('index'=>'excel_fenghao',      'open'=>'open3',    'Suffix'=>'php',      'name'=>'excel封号'),
	),
    '常用配置'=>array(
        array('index'=>'xiangou_confs',               'open'=>'open2',    'Suffix'=>'php',      'name'=>'常用限购配置'),
        array('index'=>'ht_common_gift_conf',          'open'=>'open2',    'Suffix'=>'php',      'name'=>'常用礼包配置'),
        array('index'=>'ht_excelonekeykaifu',         'open'=>'open2',    'Suffix'=>'php',      'name'=>'[配置excel一键开服]'),
        array('index'=>'excel_onekey',                'open'=>'open2',    'Suffix'=>'php',      'name'=>'[执行excel一键开服]'),
        array('index'=>'excel_onekeyshoplimit',         'open'=>'open3',    'Suffix'=>'php',      'name'=>'[配置excel一键限购]'),
        array('index'=>'ht_pingbi_conf',                'open'=>'open2',    'Suffix'=>'php',      'name'=>'配置活动 屏蔽配置'),
    ),
    '邮件ID审批'=>array(
        array('index'=>'email_send',                   'open'=>'open3',    'Suffix'=>'php',     'name'=>'邮件发送'),
        array('index'=>'newweb/v_emailsp_list',               'open'=>'open3',    'Suffix'=>'php',      'name'=>'申请列表'),
        array('index'=>'newweb/v_emailsp',               'open'=>'open3',    'Suffix'=>'php',      'name'=>'邮件审批'),
    ),
    '修改密码'=>array(
        array('index'=>'changePass',                  'open'=>'open1',    'Suffix'=>'html',     'name'=>'修改密码'),
    ),
    '后台管理'=>array(
        array('index'=>'newweb/v_admin_conf',         'open'=>'open3',    'Suffix'=>'php',      'name'=>'用户权限管理'),
    ),
);

